[project]
name = "master-thesis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "asyncio>=4.0.0",
    "chromadb>=1.5.9",
    "docker>=7.1.0",
    "neo4j>=6.2.0",
    "numpy>=2.4.5",
    "pgvector>=0.5.0",
    "psycopg[binary]>=3.3.4",
    "redis>=8.1.0",
    "ruff>=0.15.12",
]
